// 🌍 DICTIONNAIRE DE TRADUCTION CENTRALISÉ
export const TRANSLATIONS = {
    fr: {
        retourHub: "⬅️ Retour au Tableau de bord",
        titreLogin: "Créer votre profil sécurisé",
        lblPin: "Code PIN d'accès (Optionnel) :",
        btnSubmitLogin: "Enregistrer et Déverrouiller",
        btnChronoLink: "⏱️ Module Chronomètre & Agenda",
        btnTravelLink: "🌍 Module Congo Travel Planner",
        btnLogout: "Changer de profil 🔄",
        titreChrono: "Chronomètre",
        titreAgenda: "Rappel de Rendez-vous",
        btnAddAgenda: "Ajouter à l'agenda",
        btnToggleAgendaShow: "Afficher mes rendez-vous 👁️",
        btnToggleAgendaHide: "Masquer les données 🙈",
        titreCapteurs: "🧭 Géolocalisation & Boussole",
        btnGps: "Activer mon GPS / GPRS 🛰️",
        posGeodesique: "Position Géodésique :",
        btnBoussole: "Activer la Boussole 🧭",
        titreTravel: "🌍 Congo Travel Planner",
        lblChoice: "Type de calcul de routage :",
        optChoice1: "Calculer la distance entre deux villes",
        optChoice2: "Calculer le vecteur depuis Kinshasa",
        lblDepart: "Ville Départ :",
        lblArrivee: "Ville Arrivée :",
        lblEtatRoute: "État de la route :",
        optRoad1: "Bon (Asphalte / Stable)",
        optRoad2: "Moyen (Piste praticable)",
        optRoad3: "Mauvais (Critique) ⚠️ Vecteur Air recommandé",
        lblTransport: "Vecteur de Transport :",
        optTrans1: "Véhicule (Car)",
        optTrans2: "Aéronef (Plane)",
        optTrans3: "Moto (Motorcycle)",
        btnCalculer: "Calculer la cinématique 🚀"
    },
    en: {
        retourHub: "⬅️ Back to Dashboard",
        titreLogin: "Create your secure profile",
        lblPin: "Access PIN Code (Optional):",
        btnSubmitLogin: "Register and Unlock",
        btnChronoLink: "⏱️ Stopwatch & Schedule Module",
        btnTravelLink: "🌍 Congo Travel Planner Module",
        btnLogout: "Change profile 🔄",
        retourHub: "⬅️ Back to Dashboard",
        titreChrono: "Stopwatch",
        titreAgenda: "Appointment Reminder",
        btnAddAgenda: "Add to schedule",
        btnToggleAgendaShow: "Show my appointments 👁️",
        btnToggleAgendaHide: "Hide secure data 🙈",
        titreCapteurs: "🧭 Geolocation & Compass",
        btnGps: "Activate GPS / GPRS 🛰️",
        posGeodesique: "Geodetic Position:",
        btnBoussole: "Activate Compass 🧭",
        titreTravel: "🌍 Congo Travel Planner",
        lblChoice: "Routing calculation type:",
        optChoice1: "Calculate distance between two cities",
        optChoice2: "Calculate vector from Kinshasa",
        lblDepart: "Start City:",
        lblArrivee: "Destination City:",
        lblEtatRoute: "Road Status:",
        optRoad1: "Good (Asphalt / Stable)",
        optRoad2: "Average (Passable track)",
        optRoad3: "Bad (Critical) ⚠️ Air Vector Recommended",
        lblTransport: "Transport Vector:",
        optTrans1: "Vehicle (Car)",
        optTrans2: "Aircraft (Plane)",
        optTrans3: "Motorcycle",
        btnCalculer: "Calculate kinematics 🚀"
    }
};